### ISSUE TITLE
Question about how to generate 2D feature map for training VisibNet

### ISSUE THREAD

**Issue by JiahaoXia** [francescopittaluga/invsfm#3]
Thanks for your great work! After reading your paper, I have some questions regarding how to generate a 2D feature map for training VisibNet.
When 3D point cloud is projected into a 2D feature map, I believe some 3D points will gather together on the 2D map, i.e., many 3D points--->one 2D point, some of the 3D points are on the foreground and they can be visible, while some are on the background and they cannot be seen. Under the circumstances, how to label the 2D point with "visible" or "occluded"?

**Comment by francescopittaluga** [comment]
We used COLMAP to generate a dense triangulated mesh for each scene. The mesh was then treated as ground-truth and used to assign a "visible" or "occluded" label to each 2D point. If a 2D point lies within 5% of the depth value in the mesh, then the point is assigned "visible". Otherwise, it is assigned "occluded".
